spring.application.name=monolith
spring.datasource.driver-class-name=org.postgresql.Driver

# swagger
springdoc.swagger-ui.path=/docs

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

info.app.name=A Monolithic Spring Boot Application
info.app.description=A simple monolithic application built with Spring Boot
info.app.version=1.0.0
info.app.author=Firomsa Assefa