spring.application.name=monolith
spring.datasource.driver-class-name=org.postgresql.Driver

# cache
spring.cache.type=redis
cache.ttl.products=5
cache.ttl.low-stock=5
cache.ttl.monolith-value=10
cache.ttl.categories=30

# swagger
springdoc.swagger-ui.path=/docs

management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

# Health indicators
management.health.db.enabled=true
management.health.diskspace.enabled=true
management.health.ping.enabled=true

info.app.name=monolith Management System
info.app.description=A simple monolith management system built with Spring Boot and PostgreSQL.
info.app.version=1.0.0
info.app.author=Firomsa Assefa

# Logging configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [correlationId=%X{correlationId:-NA}] %msg%n
logging.level.com.firomsa.monolith=INFO
logging.level.org.springframework.security=WARN

# Audit logging configuration
audit.logging.enabled=true
audit.logging.retention-days=90

# OTP configuration
app.otp.duration=15