spring.config.activate.on-profile=dev

logging.level.root=DEBUG

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# database  
spring.datasource.url=jdbc:postgresql://localhost:5432/monolith
spring.datasource.username=postgres
spring.datasource.password=password

# swagger
springdoc.swagger-ui.enabled=true

# s3
spring.cloud.aws.credentials.access-key=test-access-key
spring.cloud.aws.credentials.secret-key=test-secret-key
spring.cloud.aws.s3.region=us-east-1
spring.cloud.aws.s3.endpoint=http://localhost:9000
spring.cloud.aws.s3.path-style-access-enabled=true
s3.bucket-name="test-bucket"
s3.get-link-expiry-minutes=10
s3.upload-link-expiry-minutes=2

# mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.auth=false  

# admin contact
admin.email=admin@example.com
admin.phone=+251900000000

# Security
auth.secret=f53603ddb1c5c52f094cf7d510b66df2fcd583804b8a00893f668c27108321d6
cors.origins=http://localhost:8080
app.bootstrap.token=f53603ddb1c5c52f094cf7d510b66df2fcd583804b8a00893f668c27108321d5

