-- Initial schema for the monolith backend.
-- Mirrors the JPA entities in com.firomsa.monolith.model.
-- Hibernate runs in `validate` mode against this schema.

-- Sequences for Integer @GeneratedValue ids (Hibernate AUTO -> SEQUENCE, allocationSize 50).
CREATE SEQUENCE roles_seq INCREMENT BY 50 START WITH 1 MINVALUE 1;
CREATE SEQUENCE confirmation_otps_seq INCREMENT BY 50 START WITH 1 MINVALUE 1;

-- roles
CREATE TABLE roles (
    id   INTEGER      NOT NULL DEFAULT nextval('roles_seq'),
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

-- users
CREATE TABLE users (
    id         UUID         NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    image_key  VARCHAR(255),
    active     BOOLEAN      NOT NULL,
    enabled    BOOLEAN      NOT NULL,
    role_id    INTEGER,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

-- refresh_tokens
CREATE TABLE refresh_tokens (
    id         UUID NOT NULL,
    user_id    UUID,
    created_at TIMESTAMP(6),
    token      TEXT,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- confirmation_otps
CREATE TABLE confirmation_otps (
    id         INTEGER      NOT NULL DEFAULT nextval('confirmation_otps_seq'),
    otp        VARCHAR(255) NOT NULL,
    confirmed  BOOLEAN      NOT NULL,
    user_id    UUID,
    created_at TIMESTAMP(6),
    expires_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_confirmation_otps PRIMARY KEY (id),
    CONSTRAINT fk_confirmation_otps_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- audit_logs
CREATE TABLE audit_logs (
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    correlation_id UUID        NOT NULL,
    user_id       UUID,
    username      VARCHAR(255),
    action        VARCHAR(255) NOT NULL,
    resource_type VARCHAR(100),
    resource_id   UUID,
    old_value     JSONB,
    new_value     JSONB,
    ip_address    VARCHAR(45),
    user_agent    VARCHAR(500),
    timestamp     TIMESTAMP(6) NOT NULL,
    status        VARCHAR(255) NOT NULL,
    error_message TEXT,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

-- Indexes declared on the entity mappings.
CREATE INDEX idx_users_role ON users (role_id);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_confirmation_otps_user ON confirmation_otps (user_id);
CREATE INDEX idx_audit_correlation_id ON audit_logs (correlation_id);
CREATE INDEX idx_audit_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_action ON audit_logs (action);
CREATE INDEX idx_audit_resource_type ON audit_logs (resource_type);
CREATE INDEX idx_audit_timestamp ON audit_logs (timestamp);
CREATE INDEX idx_audit_status ON audit_logs (status);
